import { Geist, Poppins } from "next/font/google";
import "./globals.css";
import toast, { Toaster } from 'react-hot-toast';

const pop = Poppins({
  weight:"300",
  subsets:["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${pop.className} antialiased`}>
          <Toaster />
        {children}
      </body>
    </html>
  );
}
